import ProductCard from "../components/ui/ProductCard";

const productDataArray = [
  {
    id: 2871127,
    productDetails1Id: 0,
    inExpNo: "KSN/09796/24-25",
    soNo: null,
    customerName: null,
    customerContact: null,
    salesPersonName: null,
    salesPersonContact: null,
    inCmName: "Ramakrishana Ornaments|MP-B|Rewa",
    inDt: null,
    omTc: null,
    omYy: null,
    omChr: null,
    priceType: "MRP",
    omNo: null,
    odsr: null,
    dmctg: "Sun Rise Pendent",
    odDmCd: "KP20522",
    kt: "18KT - Y",
    odKt: "18KT",
    odDmCol: "Y",
    inCmCd: "",
    grossWt: 0.37,
    diaWt: 0.01,
    diaQty: 1,
    rmCtg1: "SI",
    odOrdQty: 1.0,
    mrp: 5500.0,
    odSalPrc: 4316.0,
    finalPrc: 4262.3,
    inTotRs: 1262337.0,
    cgst: 0.0,
    sgst: 0.0,
    igst: 127.87,
    tcs: 0.0,
    cdCertNo: "58J7111924\nJSO/24/KSN/10006",
    huidNo: "79XA7I",
    igino: "58J7111924",
    ordNo: "JSO/24/KSN/10006",
    collectionName: "FLORA",
    colWt: 0.0,
    otherWt: 0.0,
    netWt: 0.37,
    checkbox: false,
    isPick: null,
    soitem: null,
    oldDp: 4262.3,
    purity: 0.75,
    subMrp: 5339.80583,
    oldMRP: 5500.0,
    makingCharge: 0.0,
    materialName: "DIAMOND",
    soid: 0,
    storeId: null,
    goldMrp: 0.0,
    goldDp: 0.0,
    goldMargin: 0.0,
    diaMrp: 0.0,
    diaDp: 0.0,
    diaMargin: 0.0,
    labMrp: 0.0,
    labDp: 0.0,
    tag: "Promo",
    labMargin: 0.0,
    colorStonePrice: null,
    currentGoldPrice: 2348.76,
    marginAddedDP: null,
    isSNMCC: null,
    isSNMCCProd: null,
    isSNMCCFormat: "N",
    image_path: "https://assets.kisna.com/public/uploads/Product/KP20522.png",
  },
  {
    id: 2871131,
    productDetails1Id: 0,
    inExpNo: "KSN/09796/24-25",
    soNo: null,
    customerName: null,
    customerContact: null,
    salesPersonName: null,
    salesPersonContact: null,
    inCmName: "Ramakrishana Ornaments|MP-B|Rewa",
    inDt: null,
    omTc: null,
    omYy: null,
    omChr: null,
    priceType: "MRP",
    omNo: null,
    odsr: null,
    dmctg: "Sun Spring Ring",
    odDmCd: "KR11339",
    kt: "18KT - Y",
    odKt: "18KT",
    odDmCol: "Y",
    inCmCd: "R13.5",
    grossWt: 1.09,
    diaWt: 0.02,
    diaQty: 4,
    rmCtg1: "SI",
    odOrdQty: 1.0,
    mrp: 14200.0,
    odSalPrc: 11143.0,
    finalPrc: 11004.47,
    inTotRs: 1262337.0,
    cgst: 0.0,
    sgst: 0.0,
    igst: 330.13,
    tcs: 0.0,
    cdCertNo: "58J2994324\nJSO/24/KSN/10007",
    huidNo: "PFCWA3",
    igino: "58J2994324",
    ordNo: "JSO/24/KSN/10007",
    collectionName: "Bandhan Collection-4",
    colWt: 0.0,
    otherWt: 0.0,
    netWt: 1.09,
    checkbox: false,
    isPick: null,
    soitem: null,
    oldDp: 11004.47,
    purity: 0.75,
    subMrp: 13786.40777,
    oldMRP: 14200.0,
    makingCharge: 0.0,
    materialName: "DIAMOND",
    soid: 0,
    storeId: null,
    goldMrp: 0.0,
    goldDp: 0.0,
    goldMargin: 0.0,
    diaMrp: 0.0,
    diaDp: 0.0,
    diaMargin: 0.0,
    labMrp: 0.0,
    labDp: 0.0,
    tag: "Promo",
    labMargin: 0.0,
    colorStonePrice: null,
    currentGoldPrice: 6919.32,
    marginAddedDP: null,
    isSNMCC: null,
    isSNMCCProd: null,
    isSNMCCFormat: "N",
    image_path: "https://assets.kisna.com/public/uploads/Product/KR11339.png",
  },
  {
    id: 2871132,
    productDetails1Id: 0,
    inExpNo: "KSN/09796/24-25",
    soNo: null,
    customerName: null,
    customerContact: null,
    salesPersonName: null,
    salesPersonContact: null,
    inCmName: "Ramakrishana Ornaments|MP-B|Rewa",
    inDt: null,
    omTc: null,
    omYy: null,
    omChr: null,
    priceType: "MRP",
    omNo: null,
    odsr: null,
    dmctg: "EARRING",
    odDmCd: "KE40484E",
    kt: "18KT - Y",
    odKt: "18KT",
    odDmCol: "Y",
    inCmCd: "RS",
    grossWt: 1.28,
    diaWt: 0.04,
    diaQty: 8,
    rmCtg1: "SI",
    odOrdQty: 1.0,
    mrp: 17100.0,
    odSalPrc: 13419.0,
    finalPrc: 13251.87,
    inTotRs: 1262337.0,
    cgst: 0.0,
    sgst: 0.0,
    igst: 397.56,
    tcs: 0.0,
    cdCertNo: "57J9957124\nJSO/24/KSN/10007",
    huidNo: "9PTUDF, L9YYZE",
    igino: "57J9957124",
    ordNo: "JSO/24/KSN/10007",
    collectionName: "Bandhan Collection-4",
    colWt: 0.0,
    otherWt: 0.0,
    netWt: 1.27,
    checkbox: false,
    isPick: null,
    soitem: null,
    oldDp: 13251.87,
    purity: 0.75,
    subMrp: 16601.94175,
    oldMRP: 17100.0,
    makingCharge: 0.0,
    materialName: "DIAMOND",
    soid: 0,
    storeId: null,
    goldMrp: 0.0,
    goldDp: 0.0,
    goldMargin: 0.0,
    diaMrp: 0.0,
    diaDp: 0.0,
    diaMargin: 0.0,
    labMrp: 0.0,
    labDp: 0.0,
    tag: "Promo",
    labMargin: 0.0,
    colorStonePrice: null,
    currentGoldPrice: 8061.96,
    marginAddedDP: null,
    isSNMCC: null,
    isSNMCCProd: null,
    isSNMCCFormat: "N",
    image_path:
      "https://assets.kisna.com/public/uploads/Product/KE40484E_P.png",
  },
  {
    id: 2871133,
    productDetails1Id: 0,
    inExpNo: "KSN/09796/24-25",
    soNo: null,
    customerName: null,
    customerContact: null,
    salesPersonName: null,
    salesPersonContact: null,
    inCmName: "Ramakrishana Ornaments|MP-B|Rewa",
    inDt: null,
    omTc: null,
    omYy: null,
    omChr: null,
    priceType: "MRP",
    omNo: null,
    odsr: null,
    dmctg: "Sun Rose Nose Pin",
    odDmCd: "S55506S",
    kt: "18KT - Y",
    odKt: "18KT",
    odDmCol: "Y",
    inCmCd: "RS",
    grossWt: 0.45,
    diaWt: 0.04,
    diaQty: 1,
    rmCtg1: "SI",
    odOrdQty: 1.0,
    mrp: 8400.0,
    odSalPrc: 6592.0,
    finalPrc: 6509.69,
    inTotRs: 1262337.0,
    cgst: 0.0,
    sgst: 0.0,
    igst: 195.29,
    tcs: 0.0,
    cdCertNo: "58J2993424\nJSO/24/KSN/10007",
    huidNo: "88FWU3",
    igino: "58J2993424",
    ordNo: "JSO/24/KSN/10007",
    collectionName: "Siva Premium",
    colWt: 0.0,
    otherWt: 0.0,
    netWt: 0.44,
    checkbox: false,
    isPick: null,
    soitem: null,
    oldDp: 6509.69,
    purity: 0.75,
    subMrp: 8155.33981,
    oldMRP: 8400.0,
    makingCharge: 0.0,
    materialName: "DIAMOND",
    soid: 0,
    storeId: null,
    goldMrp: 0.0,
    goldDp: 0.0,
    goldMargin: 0.0,
    diaMrp: 0.0,
    diaDp: 0.0,
    diaMargin: 0.0,
    labMrp: 0.0,
    labDp: 0.0,
    tag: "Promo",
    labMargin: 0.0,
    colorStonePrice: null,
    currentGoldPrice: 2793.12,
    marginAddedDP: null,
    isSNMCC: null,
    isSNMCCProd: null,
    isSNMCCFormat: "N",
    image_path: "https://assets.kisna.com/public/uploads/Product/S55506S.jpg",
  },
];

export const Products = () => (
  <div className="bg-white rounded-xl shadow-sm p-6">
    <h2 className="text-xl sm:text-2xl font-semibold text-gray-900 mb-4">
      Products Page
    </h2>
    <p className="text-gray-700 text-sm sm:text-base">
      "The Products page is under development. We're excited to introduce a new
      collection of jewelry products. Please check back soon for our latest
      arrivals!"
    </p>
    <div className="flex flex-wrap justify-center">
      {" "}
      {/* Center the cards */}
      {productDataArray.map((product, index) => (
        <ProductCard key={index} productData={product} />
      ))}
    </div>
  </div>
);
